### ISSUE TITLE
Dstat config file 

### ISSUE THREAD

**Issue by noproblem666** [peelframework/peel#100]
Hi,

we want to use Dstat as a dependency for Flink to get fine grained resource statistics. Unfortunately, Peel has no default or example configuration for Dstat. If we just use the provided Dstat reference config an error occur. Does anyone has an example configuration file for dstat? 

Thanks!

**Comment by aalexandrov** [comment]
What error?

**Comment by lauritzthamsen** [comment]
we're using _dstat-0.7.2_ via the `reference.dstat-0.7.2.conf` (which is a default config, isn't it?). the only thing our cluster-specific dstat config sets is `system.dstat.config.out.dir`.

**Comment by noproblem666** [comment]
The error is: `No configuration setting found for key 'system.dstat.path.log'`

**Comment by aalexandrov** [comment]
I removed this setting when I reworked the DStat system implementation (see 6b7d9725572f44080a0b214a446b0851e2ce5d27).

Can you verify that the `Dstat` system bean that you have included in your bundle [is the latest version](https://github.com/peelframework/peel/blob/6b7d9725572f44080a0b214a446b0851e2ce5d27/peel-extensions/src/main/scala/org/peelframework/dstat/beans/system/Dstat.scala)?

Maybe you have an old version of `peel-extensions` in the `$BUNDLE_BIN/lib` folder?

**Comment by noproblem666** [comment]
I have recompiled the latest version of the `peel-extensions` project and them copied to the `$BUNDLE_BIN/lib` folder. However the error message appears. 
```log
Unexpected error: No configuration setting found for key 'system.dstat.path.log'
com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'system.dstat.path.log'
       	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
       	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145)
       	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
       	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
       	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:151)
       	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
       	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
       	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:206)
       	at org.peelframework.core.beans.system.System.copyHomeToSlaves(System.scala:97)
       	at org.peelframework.core.beans.system.System.setUp(System.scala:85)
       	at org.peelframework.core.cli.command.experiment.Run$$anonfun$run$3$$anonfun$apply$1$$anonfun$apply$12.apply(Run.scala:161)
       	at org.peelframework.core.cli.command.experiment.Run$$anonfun$run$3$$anonfun$apply$1$$anonfun$apply$12.apply(Run.scala:160)
       	at scala.collection.immutable.List.foreach(List.scala:318)
       	at org.peelframework.core.cli.command.experiment.Run$$anonfun$run$3$$anonfun$apply$1.apply(Run.scala:160)
       	at org.peelframework.core.cli.command.experiment.Run$$anonfun$run$3$$anonfun$apply$1.apply(Run.scala:94)
       	at scala.Option.foreach(Option.scala:236)
       	at org.peelframework.core.cli.command.experiment.Run$$anonfun$run$3.apply(Run.scala:94)
       	at org.peelframework.core.cli.command.experiment.Run$$anonfun$run$3.apply(Run.scala:94)
       	at scala.collection.immutable.Stream.foreach(Stream.scala:547)
       	at org.peelframework.core.cli.command.experiment.Run.run(Run.scala:94)
       	at org.peelframework.core.cli.Peel$.main(Peel.scala:112)
       	at org.peelframework.core.cli.Peel.main(Peel.scala)
```

I now added the following line in `system.dstat.path` to the` dstat-0.7.2.conf`: `log = ${java.io.tmpdir}"/dstat"`

Now it works fine! 

Thanks!

**Comment by aalexandrov** [comment]
It seems that your experiment configurations is referring to a non-existing variable. You can grep your codebase for `system.dstat.path.log`, but this won't match definitions that use the nested HOCON syntax, e.g.  `system { dstat { path { log = ... } } } }`.

**Comment by aalexandrov** [comment]
However, the reference should be located somewhere in the stack of files loaded for the problematic experiment.

**Comment by noproblem666** [comment]
I found no reference for `system.dstat.path.log` in my experiment configuration.
However, it works for me by setting the log path `system.dstat.path.log`in `dstat-0.7.2.conf`.

Anyway, I think you can close this issue. Thanks!

**Comment by aalexandrov** [comment]
BTW the latest Peel version (1.1.1) introduces an `exp:config` command which dumps the HOCON config used for a specific experiment. If you use the `--origin` option you can debug and see why the value is missing or is set to a bad value.
