### ISSUE TITLE
Timeout when running the Getting started example

### ISSUE THREAD

**Issue by he-sk** [peelframework/peel#101]
Hi,

I get the following error message when running the first peel.sh command in the Getting started guide:

```
16-08-30 14:28:52 [INFO] ############################################################
16-08-30 14:28:52 [INFO] #           PEEL EXPERIMENTS EXECUTION FRAMEWORK           #
16-08-30 14:28:52 [INFO] ############################################################
16-08-30 14:28:52 [INFO] Running experiments in suite 'wordcount.default'
16-08-30 14:28:52 [INFO] Constructing dependency graph for suite 'wordcount.default'
16-08-30 14:28:52 [INFO] Loading configuration for experiment 'wordcount.flink'
16-08-30 14:28:52 [INFO] +-- Loading resource reference.peel.conf
16-08-30 14:28:52 [INFO] +-- Loading resource reference.hdfs-2.7.1.conf
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/hdfs-2.7.1.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/hosts/foousers-mbp-2.bar.foo.com/hdfs-2.7.1.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Loading resource reference.flink-0.9.0.conf
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/flink-0.9.0.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/hosts/foousers-mbp-2.bar.foo.com/flink-0.9.0.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/application.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/hosts/foousers-mbp-2.bar.foo.com/application.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Loading experiment configuration
16-08-30 14:28:52 [INFO] +-- Loading current runtime values as configuration
16-08-30 14:28:52 [INFO] +-- Loading system properties as configuration
16-08-30 14:28:52 [INFO] `-- Resolving configuration
16-08-30 14:28:52 [INFO] Loading configuration for experiment 'wordcount.spark'
16-08-30 14:28:52 [INFO] +-- Loading resource reference.peel.conf
16-08-30 14:28:52 [INFO] +-- Loading resource reference.hdfs-2.7.1.conf
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/hdfs-2.7.1.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/hosts/foousers-mbp-2.bar.foo.com/hdfs-2.7.1.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Loading resource reference.spark-1.4.0.conf
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/spark-1.4.0.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/hosts/foousers-mbp-2.bar.foo.com/spark-1.4.0.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/application.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Skipping file /Users/username/Desktop/bundles/bin/someproject-benchmark/config/hosts/foousers-mbp-2.bar.foo.com/application.conf (does not exist)
16-08-30 14:28:52 [INFO] +-- Loading experiment configuration
16-08-30 14:28:52 [INFO] +-- Loading current runtime values as configuration
16-08-30 14:28:52 [INFO] +-- Loading system properties as configuration
16-08-30 14:28:52 [INFO] `-- Resolving configuration
16-08-30 14:28:52 [INFO] Executing experiments in suite
16-08-30 14:28:52 [INFO] ############################################################
16-08-30 14:28:52 [INFO] Current experiment is 'wordcount.flink'
16-08-30 14:28:52 [INFO] Setting up / updating systems required for input data sets
16-08-30 14:28:52 [INFO] Starting system 'hdfs-2.7.1'
16-08-30 14:28:52 [INFO] Downloading archive '/Users/username/Desktop/bundles/bin/someproject-benchmark/downloads/hadoop-2.7.1.tar.gz' from 'http://archive.apache.org/dist/hadoop/core/hadoop-2.7.1/hadoop-2.7.1.tar.gz' (md5: '42859070124383047548836002726164714801')
16-08-30 14:31:23 [INFO] Extracting archive '/Users/username/Desktop/bundles/bin/someproject-benchmark/downloads/hadoop-2.7.1.tar.gz' to '/Users/foouser/Desktop/bundles/bin/someproject-benchmark/systems'
16-08-30 14:31:25 [INFO] Changing owner of '/Users/username/Desktop/bundles/bin/someproject-benchmark/systems/hadoop-2.7.1' to foouser:foouser
16-08-30 14:31:25 [INFO] Updating configuration entry at /Users/username/Desktop/bundles/bin/someproject-benchmark/systems/hadoop-2.7.1/etc/hadoop/slaves
16-08-30 14:31:25 [INFO] Updating configuration entry at /Users/username/Desktop/bundles/bin/someproject-benchmark/systems/hadoop-2.7.1/etc/hadoop/hadoop-env.sh
16-08-30 14:31:25 [INFO] Updating configuration entry at /Users/username/Desktop/bundles/bin/someproject-benchmark/systems/hadoop-2.7.1/etc/hadoop/core-site.xml
16-08-30 14:31:25 [INFO] Updating configuration entry at /Users/username/Desktop/bundles/bin/someproject-benchmark/systems/hadoop-2.7.1/etc/hadoop/hdfs-site.xml
16-08-30 14:31:25 [INFO] Formatting namenode
16-08-30 14:31:26 [INFO] Initializing HDFS data directory '/tmp/hdfs-2/data' at usernames-mbp-2.bar.foo.com
16-08-30 14:31:56 [ERROR] Exception for experiment 'wordcount.flink' in suite 'wordcount.default': Futures timed out after [30 seconds]
16-08-30 14:31:56 [INFO] Tearing down systems with EXPERIMENT lifespan
16-08-30 14:31:56 [INFO] System 'flink-0.9.0' is already down
16-08-30 14:31:56 [ERROR] Exception in suite 'wordcount.default': Futures timed out after [30 seconds]
16-08-30 14:31:56 [INFO] ############################################################
16-08-30 14:31:56 [INFO] Tearing down systems with SUITE lifespan
16-08-30 14:31:56 [INFO] System 'hdfs-2.7.1' is already down
Unexpected error: Futures timed out after [30 seconds]
java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.Await$.result(package.scala:107)
	at org.peelframework.hadoop.beans.system.HDFS2.format(HDFS2.scala:177)
	at org.peelframework.hadoop.beans.system.HDFS2.start(HDFS2.scala:89)
	at org.peelframework.core.beans.system.System.setUp(System.scala:86)
	at org.peelframework.core.cli.command.suite.Run$$anonfun$run$2$$anonfun$apply$6.apply(Run.scala:98)
	at org.peelframework.core.cli.command.suite.Run$$anonfun$run$2$$anonfun$apply$6.apply(Run.scala:97)
	at scala.collection.immutable.Set$Set1.foreach(Set.scala:74)
	at org.peelframework.core.cli.command.suite.Run$$anonfun$run$2.apply(Run.scala:97)
	at org.peelframework.core.cli.command.suite.Run$$anonfun$run$2.apply(Run.scala:79)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.peelframework.core.cli.command.suite.Run.run(Run.scala:79)
	at org.peelframework.core.cli.Peel$.main(Peel.scala:112)
	at org.peelframework.core.cli.Peel.main(Peel.scala)
```

The command I ran was:

```
./peel.sh suite:run wordcount.default
```

I installed peel by cloning the current Github sources, checking out the tag v1.0.0, and then running `mvn install`. The only change I made is that I use `~/Desktop/bundles` for `$BUNDLE_{BIN,SRC}`.

Viktor

**Comment by aalexandrov** [comment]
The critical lines are 

```
16-08-30 14:31:26 [INFO] Initializing HDFS data directory '/tmp/hdfs-2/data' at usernames-mbp-2.bar.foo.com
16-08-30 14:31:56 [ERROR] Exception for experiment 'wordcount.flink' in suite 'wordcount.default': Futures timed out after [30 seconds]
```

Usually this indicates that your ssh configuration prompts for a password.

Go to `$BUNDLE_BIN/log/shell.in`, look for a command that has the form

```bash
ssh $user@$host "rm -Rf /tmp/hdfs-2/data && mkdir -p /tmp/hdfs-2/data/current"
```

and try to execute it manually. The command should be able to run in a non-interactive mode, and for that you will need [passwordless ssh](http://www.linuxproblem.org/art_9.html).

Another problem that we saw on macs is that per default their $HOSTNAME is not set in `/etc/hostname`, and inherits the one given by the current network. 

You might want to change this if you want to use your machine for Peel bundle development.

**Comment by he-sk** [comment]
Thanks, that helped.
